name: Build and Push Docker to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-1  # Zmień region na odpowiedni dla testów
  ECR_REGISTRY: "123456789012.dkr.ecr.us-east-1.amazonaws.com"  # Placeholder AWS Account ID

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        run: |
          echo "Placeholder: Simulated AWS ECR login"

      - name: Build Docker image
        run: |
          echo "Building Docker image"
          docker build -t test-image .

      - name: Tag and Push to ECR
        run: |
          echo "Simulating Docker push"
          echo "Pushed image: $ECR_REGISTRY/test-image:latest"
