name: Build docker ECR

on:
  workflow_dispatch:

jobs:
  docker:
    name: Build & push docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simulate AWS Login
        run: echo "Simulating AWS login for testing."

      - name: Simulate ECR Login
        if: ${{ inputs.ECR_REPOSITORY }}
        run: echo "Simulating ECR login for repository ${{ inputs.ECR_REPOSITORY }}."

      - name: Remove slash from DOCKER_TAG_1 and trim to 128 characters
        id: tag_trim1
        run: |
          DOCKER_TAG_1_NO_SLASH=$(echo ${{ inputs.DOCKER_TAG_1 }} | sed 's#/#-#g')
          DOCKER_TAG_1_TRIMMED="${DOCKER_TAG_1_NO_SLASH:0:127}"
          echo "DOCKER_TAG_1_TRIMMED=${DOCKER_TAG_1_TRIMMED}" >> $GITHUB_ENV

      - name: Docker image build
        id: docker_build
        env:
          DOCKER_ARGS: "--no-cache"
        run: |
          docker build -f Dockerfile -t local_image .
        working-directory: .

      - name: Simulate Docker Push
        if: ${{ inputs.ECR_REPOSITORY != '' }}
        run: |
          echo "Simulating docker push for ${{ inputs.ECR_REPOSITORY }}."
