name: Build docker ECR (Test Version)
on:
  workflow_call:
    inputs:
      CHECKOUT_GIT_REF:
        type: string
        required: true
        description: "Can be: commit hash, refs/tags/CUSTOM_TAG or BRANCH_NAME"
      AWS_ACCOUNT_ID:
        type: string
        required: true
        description: "AWS account id"
      DEPLOYER_ROLE_NAME:
        type: string
        required: true
        description: "AWS IAM deployer role in AWS account"
      BEFORE_BUILD_CMD:
        type: string
        required: false
        description: "Optional before build command to run"
      AWS_REGION:
        type: string
        required: true
        description: "AWS region"
      ECR_REPOSITORY:
        type: string
        required: false
        description: "Name of ECR repository where docker image will be pushed."
      DOCKER_TAG_1:
        type: string
        required: true
        description: "Name of docker image tag1 which will be pushed to ECR."
      DOCKER_TAG_2:
        type: string
        required: false
        description: "(Optional) Name of docker image tag2 which will be pushed to ECR."
      DOCKER_LATEST_TAG:
        type: string
        required: false
        default: "latest"
        description: "Name of default latest docker image which will be pushed to ECR."
      RUNNER_LABEL_ARRAY_STRING:
        type: string
        required: true
        description: "Runner labels array. E.g. [\"ubuntu-latest\"]"
    secrets:
      DOCKER_BUILD_ARGS_ENCRYPTED:
        required: false
        description: "Optional arguments to pass in to docker Command with secrets from Github."

permissions:
  id-token: write
  contents: write

env:
  DEPLOYER_ROLE_ARN: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.DEPLOYER_ROLE_NAME }}
  ECR_REGISTRY: ${{ inputs.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com

jobs:
  docker:
    name: Build & push docker (Test Version)
    runs-on: ${{ fromJSON(inputs.RUNNER_LABEL_ARRAY_STRING) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ inputs.CHECKOUT_GIT_REF }}

      - name: Simulate AWS Login
        if: ${{ inputs.ECR_REPOSITORY }}
        run: echo "Simulating AWS login for testing."

      - name: Simulate ECR Login
        if: ${{ inputs.ECR_REPOSITORY }}
        run: echo "Simulating ECR login for repository ${{ inputs.ECR_REPOSITORY }}."

      - name: Before build (simulated)
        if: ${{ inputs.BEFORE_BUILD_CMD != '' }}
        run: echo "Simulating before build command ${{ inputs.BEFORE_BUILD_CMD }}."

      - name: Remove slash from DOCKER_TAG_1 and trim to 128 characters
        id: tag_trim1
        run: |
          DOCKER_TAG_1_NO_SLASH=$(echo "${{ inputs.DOCKER_TAG_1 }}" | sed 's#/#-#g')  # Zamiana ukośników na myślniki
          DOCKER_TAG_1_TRIMMED=$(echo "$DOCKER_TAG_1_NO_SLASH" | cut -c -127)  # Przycięcie do 127 znaków
          echo "DOCKER_TAG_1_TRIMMED=${DOCKER_TAG_1_TRIMMED}" >> $GITHUB_ENV  # Zapisanie do zmiennej środowiskowej
          echo "DEBUG: DOCKER_TAG_1_TRIMMED=${DOCKER_TAG_1_TRIMMED}"  # Debugowanie

      - name: Debug DOCKER_TAG_1_TRIMMED
        run: |
          echo "DOCKER_TAG_1_TRIMMED=${DOCKER_TAG_1_TRIMMED}"  # Sprawdzenie, czy zmienna jest dostępna

      - name: Remove slash from DOCKER_TAG_2 and trim to 128 characters
        id: tag_trim2
        if: ${{ inputs.DOCKER_TAG_2 }}
        run: |
          DOCKER_TAG_2_NO_SLASH=$(echo "${{ inputs.DOCKER_TAG_2 }}" | sed 's#/#-#g')
          DOCKER_TAG_2_TRIMMED=$(echo "$DOCKER_TAG_2_NO_SLASH" | cut -c -127)
          echo "DOCKER_TAG_2_TRIMMED=${DOCKER_TAG_2_TRIMMED}" >> $GITHUB_ENV
          echo "DEBUG: DOCKER_TAG_2_TRIMMED=${DOCKER_TAG_2_TRIMMED}"  # Debugowanie

      - name: Debug DOCKER_TAG_2_TRIMMED
        if: ${{ inputs.DOCKER_TAG_2 }}
        run: |
          echo "DOCKER_TAG_2_TRIMMED=${DOCKER_TAG_2_TRIMMED}"  # Sprawdzenie, czy zmienna jest dostępna

      - name: Simulate Docker image build (always)
        env:
          DOCKER_ARGS: ${{ inputs.DOCKER_BUILD_ARGS }} ${{ secrets.DOCKER_BUILD_ARGS_ENCRYPTED }}
        run: |
          echo "Simulating docker build with args: $DOCKER_ARGS"
          echo "Building image with tag: local_image"
        working-directory: .

      - name: Simulate Docker image tag & push to ECR (DOCKER_TAG_1 & latest)
        if: ${{ inputs.ECR_REPOSITORY }}
        env:
          ECR_IMAGE_URI_TAG_1: ${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ env.DOCKER_TAG_1_TRIMMED }}
          ECR_IMAGE_URI_TAG_LATEST: ${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.DOCKER_LATEST_TAG }}
        run: |
          echo "Simulating docker tag for $ECR_IMAGE_URI_TAG_1 and $ECR_IMAGE_URI_TAG_LATEST"
          echo "Simulating docker push for $ECR_IMAGE_URI_TAG_1 and $ECR_IMAGE_URI_TAG_LATEST"

      - name: Simulate Docker image tag & push to ECR (DOCKER_TAG_2)
        if: ${{ inputs.ECR_REPOSITORY && inputs.DOCKER_TAG_2 }}
        env:
          ECR_IMAGE_URI_TAG_2: ${{ env.ECR_REGISTRY }}/${{ inputs.ECR_REPOSITORY }}:${{ env.DOCKER_TAG_2_TRIMMED }}
        run: |
          echo "Simulating docker tag for $ECR_IMAGE_URI_TAG_2"
          echo "Simulating docker push for $ECR_IMAGE_URI_TAG_2"