name: Test Build Docker ECR Logic - With DOCKER_BUILD_ARGS_ENCRYPTED

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  test_logic:
    name: Test Build Logic - With DOCKER_BUILD_ARGS_ENCRYPTED
    uses: ./.github/workflows/build-docker-ecr.yml
    with:
      CHECKOUT_GIT_REF: "main"
      AWS_ACCOUNT_ID: "123456789012"
      DEPLOYER_ROLE_NAME: "mock-role"
      AWS_REGION: "us-east-1"
      ECR_REPOSITORY: "my-repo"
      DOCKER_TAG_1: "wacver/yxlongxtagxthatxexceedx128xcha/ractersxabcdefghijklmnopqrstuvwxyzx1234567890xABCDEFGHIJKLMNOPQRSTUVWXYZ"
      DOCKER_TAG_2: ""
      RUNNER_LABEL_ARRAY_STRING: '["ubuntu-latest"]'
    secrets:
      DOCKER_BUILD_ARGS_ENCRYPTED: "mock-encrypted-args"