name: Test Build Docker ECR Logic

on:
  workflow_dispatch: # Pozwala uruchomić ręcznie

jobs:
  test_logic:
    name: Test Build Logic
    uses: ./.github/workflows/build-docker-ecr.yml
    with:
      CHECKOUT_GIT_REF: "main" # Testujemy na głównej gałęzi
      AWS_ACCOUNT_ID: "123456789012" # Mockowe dane
      DEPLOYER_ROLE_NAME: "mock-role"
      AWS_REGION: "us-east-1"
      ECR_REPOSITORY: "mock-repo"
      DOCKER_TAG_1: "mock-tag"
      DOCKER_TAG_2: "optional-mock-tag"
      DOCKER_LATEST_TAG: "latest"
      RUNNER_LABEL_ARRAY_STRING: "[\"ubuntu-latest\"]"
