name: Test Build Docker ECR Logic

on:
  workflow_dispatch: # Pozwala uruchomić ręcznie

jobs:
  test_logic:
    name: Test Build Logic
    uses: ./.github/workflows/build-docker-ecr.yml # Wywołanie reusable workflow
    with:
      CHECKOUT_GIT_REF: "main"
      AWS_ACCOUNT_ID: "123456789012"
      DEPLOYER_ROLE_NAME: "mock-role"
      AWS_REGION: "us-east-1"
      ECR_REPOSITORY: "mock-repo"
      DOCKER_TAG_1: "mock-tag"
      DOCKER_TAG_2: "optional-mock-tag"
      RUNNER_LABEL_ARRAY_STRING: "[\"ubuntu-latest\"]"
      BEFORE_BUILD_CMD: "echo 'Before build command executed!'"
      DOCKER_FILE_NAME: "Dockerfile"
